#ifndef _ARM_LOCAL_H_
#define _ARM_LOCAL_H_

#include <stdint.h>
#include <hal/address.h>

#define ARM_LOCAL_ARM_CONTROL           (ARM_LOCAL_BASE + 0x00)
#define ARM_LOCAL_CORE_IRQ_CONTROL      (ARM_LOCAL_BASE + 0x0C)
#define ARM_LOCAL_PMU_CONTROL_SET       (ARM_LOCAL_BASE + 0x10)
#define ARM_LOCAL_PMU_CONTROL_CLR       (ARM_LOCAL_BASE + 0x14)
#define ARM_LOCAL_PERI_IRQ_ROUTE0       (ARM_LOCAL_BASE + 0x24)
#define ARM_LOCAL_AXI_QUIET_TIME        (ARM_LOCAL_BASE + 0x30)
#define ARM_LOCAL_LOCAL_TIMER_CONTROL   (ARM_LOCAL_BASE + 0x34)
#define ARM_LOCAL_LOCAL_TIMER_IRQ       (ARM_LOCAL_BASE + 0x38)
#define ARM_LOCAL_TIMER_CNTRL0          (ARM_LOCAL_BASE + 0x40)
#define ARM_LOCAL_TIMER_CNTRL1          (ARM_LOCAL_BASE + 0x44)
#define ARM_LOCAL_TIMER_CNTRL2          (ARM_LOCAL_BASE + 0x48)
#define ARM_LOCAL_TIMER_CNTRL3          (ARM_LOCAL_BASE + 0x4C)
#define ARM_LOCAL_MAILBOX_CNTRL0        (ARM_LOCAL_BASE + 0x50)
#define ARM_LOCAL_MAILBOX_CNTRL1        (ARM_LOCAL_BASE + 0x54)
#define ARM_LOCAL_MAILBOX_CNTRL2        (ARM_LOCAL_BASE + 0x58)
#define ARM_LOCAL_MAILBOX_CNTRL3        (ARM_LOCAL_BASE + 0x5C)
#define ARM_LOCAL_IRQ_SOURCE0           (ARM_LOCAL_BASE + 0x60)
#define ARM_LOCAL_IRQ_SOURCE1           (ARM_LOCAL_BASE + 0x64)
#define ARM_LOCAL_IRQ_SOURCE2           (ARM_LOCAL_BASE + 0x68)
#define ARM_LOCAL_IRQ_SOURCE3           (ARM_LOCAL_BASE + 0x6C)
#define ARM_LOCAL_FIQ_SOURCE0           (ARM_LOCAL_BASE + 0x70)
#define ARM_LOCAL_FIQ_SOURCE1           (ARM_LOCAL_BASE + 0x74)
#define ARM_LOCAL_FIQ_SOURCE2           (ARM_LOCAL_BASE + 0x78)
#define ARM_LOCAL_FIQ_SOURCE3           (ARM_LOCAL_BASE + 0x7C)




#endif //#ifndef _ARM_LOCAL_H_