#ifndef _ARMC_H_
#define _ARMC_H_

#include "address.h"
#include "../sys/utils.h"

#define ARMC_IRQ0_PENDING0   (ARMC_BASE + 0x200)
#define ARMC_IRQ0_PENDING1   (ARMC_BASE + 0x204)
#define ARMC_IRQ0_PENDING2   (ARMC_BASE + 0x208)
#define ARMC_IRQ0_SET_EN_0   (ARMC_BASE + 0x210)
#define ARMC_IRQ0_SET_EN_1   (ARMC_BASE + 0x214)
#define ARMC_IRQ0_SET_EN_2   (ARMC_BASE + 0x218)
#define ARMC_IRQ0_CLR_EN_0   (ARMC_BASE + 0x220)
#define ARMC_IRQ0_CLR_EN_1   (ARMC_BASE + 0x224)
#define ARMC_IRQ0_CLR_EN_2   (ARMC_BASE + 0x228)
#define ARMC_IRQ_STATUS0     (ARMC_BASE + 0x230)
#define ARMC_IRQ_STATUS1     (ARMC_BASE + 0x234)
#define ARMC_IRQ_STATUS2     (ARMC_BASE + 0x238)
#define ARMC_IRQ1_PENDING0   (ARMC_BASE + 0x240)
#define ARMC_IRQ1_PENDING1   (ARMC_BASE + 0x244)
#define ARMC_IRQ1_PENDING2   (ARMC_BASE + 0x248)
#define ARMC_IRQ1_SET_EN_0   (ARMC_BASE + 0x250)
#define ARMC_IRQ1_SET_EN_1   (ARMC_BASE + 0x254)
#define ARMC_IRQ1_SET_EN_2   (ARMC_BASE + 0x258)
#define ARMC_IRQ1_CLR_EN_0   (ARMC_BASE + 0x260)
#define ARMC_IRQ1_CLR_EN_1   (ARMC_BASE + 0x264)
#define ARMC_IRQ1_CLR_EN_2   (ARMC_BASE + 0x268)
#define ARMC_IRQ2_PENDING0   (ARMC_BASE + 0x280)
#define ARMC_IRQ2_PENDING1   (ARMC_BASE + 0x284)
#define ARMC_IRQ2_PENDING2   (ARMC_BASE + 0x288)
#define ARMC_IRQ2_SET_EN_0   (ARMC_BASE + 0x290)
#define ARMC_IRQ2_SET_EN_1   (ARMC_BASE + 0x294)
#define ARMC_IRQ2_SET_EN_2   (ARMC_BASE + 0x298)
#define ARMC_IRQ2_CLR_EN_0   (ARMC_BASE + 0x2A0)
#define ARMC_IRQ2_CLR_EN_1   (ARMC_BASE + 0x2A4)
#define ARMC_IRQ2_CLR_EN_2   (ARMC_BASE + 0x2A8)
#define ARMC_IRQ3_PENDING0   (ARMC_BASE + 0x2C0)
#define ARMC_IRQ3_PENDING1   (ARMC_BASE + 0x2C4)
#define ARMC_IRQ3_PENDING2   (ARMC_BASE + 0x2C8)
#define ARMC_IRQ3_SET_EN_0   (ARMC_BASE + 0x2D0)
#define ARMC_IRQ3_SET_EN_1   (ARMC_BASE + 0x2D4)
#define ARMC_IRQ3_SET_EN_2   (ARMC_BASE + 0x2D8)
#define ARMC_IRQ3_CLR_EN_0   (ARMC_BASE + 0x2E0)
#define ARMC_IRQ3_CLR_EN_1   (ARMC_BASE + 0x2E4)
#define ARMC_IRQ3_CLR_EN_2   (ARMC_BASE + 0x2E8)

#define ARMC_FIQ0_PENDING0   (ARMC_BASE + 0x300)
#define ARMC_FIQ0_PENDING1   (ARMC_BASE + 0x304)
#define ARMC_FIQ0_PENDING2   (ARMC_BASE + 0x308)
#define ARMC_FIQ0_SET_EN_0   (ARMC_BASE + 0x310)
#define ARMC_FIQ0_SET_EN_1   (ARMC_BASE + 0x314)
#define ARMC_FIQ0_SET_EN_2   (ARMC_BASE + 0x318)
#define ARMC_FIQ0_CLR_EN_0   (ARMC_BASE + 0x320)
#define ARMC_FIQ0_CLR_EN_1   (ARMC_BASE + 0x324)
#define ARMC_FIQ0_CLR_EN_2   (ARMC_BASE + 0x328)
#define ARMC_FIQ1_PENDING0   (ARMC_BASE + 0x340)
#define ARMC_FIQ1_PENDING1   (ARMC_BASE + 0x344)
#define ARMC_FIQ1_PENDING2   (ARMC_BASE + 0x348)
#define ARMC_FIQ1_SET_EN_0   (ARMC_BASE + 0x350)
#define ARMC_FIQ1_SET_EN_1   (ARMC_BASE + 0x354)
#define ARMC_FIQ1_SET_EN_2   (ARMC_BASE + 0x358)
#define ARMC_FIQ1_CLR_EN_0   (ARMC_BASE + 0x360)
#define ARMC_FIQ1_CLR_EN_1   (ARMC_BASE + 0x364)
#define ARMC_FIQ1_CLR_EN_2   (ARMC_BASE + 0x368)
#define ARMC_FIQ2_PENDING0   (ARMC_BASE + 0x380)
#define ARMC_FIQ2_PENDING1   (ARMC_BASE + 0x384)
#define ARMC_FIQ2_PENDING2   (ARMC_BASE + 0x388)
#define ARMC_FIQ2_SET_EN_0   (ARMC_BASE + 0x390)
#define ARMC_FIQ2_SET_EN_1   (ARMC_BASE + 0x394)
#define ARMC_FIQ2_SET_EN_2   (ARMC_BASE + 0x398)
#define ARMC_FIQ2_CLR_EN_0   (ARMC_BASE + 0x3A0)
#define ARMC_FIQ2_CLR_EN_1   (ARMC_BASE + 0x3A4)
#define ARMC_FIQ2_CLR_EN_2   (ARMC_BASE + 0x3A8)
#define ARMC_FIQ3_PENDING0   (ARMC_BASE + 0x3C0)
#define ARMC_FIQ3_PENDING1   (ARMC_BASE + 0x3C4)
#define ARMC_FIQ3_PENDING2   (ARMC_BASE + 0x3C8)
#define ARMC_FIQ3_SET_EN_0   (ARMC_BASE + 0x3D0)
#define ARMC_FIQ3_SET_EN_1   (ARMC_BASE + 0x3D4)
#define ARMC_FIQ3_SET_EN_2   (ARMC_BASE + 0x3D8)
#define ARMC_FIQ3_CLR_EN_0   (ARMC_BASE + 0x3E0)
#define ARMC_FIQ3_CLR_EN_1   (ARMC_BASE + 0x3E4)
#define ARMC_FIQ3_CLR_EN_2   (ARMC_BASE + 0x3E8)
#define ARMC_SWIRQ_SET       (ARMC_BASE + 0x3F0)
#define ARMC_SWIRQ_CLEAR     (ARMC_BASE + 0x3F4)

#define VC_SYSTEM_TIMER_IRQ_0   BIT(0)
#define VC_SYSTEM_TIMER_IRQ_1   BIT(1)
#define VC_SYSTEM_TIMER_IRQ_2   BIT(2)
#define VC_SYSTEM_TIMER_IRQ_3   BIT(3)
#define VC_DMA_IRQ_0            BIT(16)
#define VC_DMA_IRQ_1            BIT(17)
#define VC_DMA_IRQ_2            BIT(18)
#define VC_DMA_IRQ_3            BIT(19)
#define VC_DMA_IRQ_4            BIT(20)
#define VC_DMA_IRQ_5            BIT(21)
#define VC_DMA_IRQ_6            BIT(22)
#define VC_DMA_IRQ_7_8          BIT(23)
#define VC_DMA_IRQ_9_10         BIT(24)
#define VC_DMA_IRQ_11           BIT(25)
#define VC_DMA_IRQ_12           BIT(26)
#define VC_DMA_IRQ_13           BIT(27)
#define VC_DMA_IRQ_14           BIT(28)
#define VC_AUX_IRQ              BIT(29)
#define VC_DMA_IRQ_15           BIT(31)

#define VC_GPIO_IRQ_0           BIT(17)
#define VC_GPIO_IRQ_1           BIT(18)
#define VC_GPIO_IRQ_2           BIT(19)
#define VC_GPIO_IRQ_3           BIT(20)
#define VC_I2C_IRQ              BIT(21)
#define VC_SPI_IRQ              BIT(22)
#define VC_UART_IRQ             BIT(25)

#define VC_LOCAL_TIMER_IRQ      BIT(0)
#define VC_MAILBOX_IRQ_0        BIT(1)
#define VC_DOORBELL_IRQ_0       BIT(2)
#define VC_DOORBELL_IRQ_1       BIT(3)
#define VC_CORE0_HALT_IRQ       BIT(4)
#define VC_CORE1_HALE_IRQ       BIT(5)
#define VC_ARM_ADDR_ERR_IRQ     BIT(6)
#define VC_ARM_AXI_ERR_IRQ      BIT(7)
#define VC_SW_TRIG_INT_IRQ_0    BIT(8)
#define VC_SW_TRIG_INT_IRQ_1    BIT(9)
#define VC_SW_TRIG_INT_IRQ_2    BIT(10)
#define VC_SW_TRIG_INT_IRQ_3    BIT(11)
#define VC_SW_TRIG_INT_IRQ_4    BIT(12)
#define VC_SW_TRIG_INT_IRQ_5    BIT(13)
#define VC_SW_TRIG_INT_IRQ_6    BIT(14)
#define VC_SW_TRIG_INT_IRQ_7    BIT(15)

#endif //#ifndef _ARMC_H_